Adding new HWO Input Catalog
danielapai/bioverse pull request #53
Opened 2024-05-16 21:39 UTC by nwtuchow

I've added the HPIC: The Habitable Worlds Preliminary Input Catalog of Tuchow, Stark, and Mamajek (2024) to the data directory and added a function to read it in functions.py.  This branch added the functionality to use a new input catalog and does not affect other areas of Bioverse. I've tested the new function and it appears to work properly.

The file size of the HPIC.txt file has been reduced to only include the relevant properties that Bioverse uses. If there are additional stellar properties from the full HPIC catalog (hosted [here](https://exoplanetarchive.ipac.caltech.edu/docs/MissionStellar.html)) which would be useful for Bioverse please let me know.

2024-05-21 21:02 UTC, kevinkhu requested changes
For consistency with the other functions, I recommend changing `dist_max` to `d_max`. Also, either change `m_V_max` to `Vmag_max` or change the magnitude names in HPIC.txt to `m_V`, `m_J`, etc. Otherwise, addition of this function and the HPIC.txt file does not affect the rest of the Bioverse code and can be merged.

2024-05-21 21:10 UTC, nwtuchow commented
If I make these changes to my HPIC_integration branch, will it automatically update it in this pull request, or would I need to may a new request?

2024-05-21 23:03 UTC, matiscke commented
@nwtuchow, if you just push a new commit to your fork `nwtuchow:HPIC_integration`, the new commit should automatically show up here and become part of this PR.

2024-05-21 23:07 UTC, nwtuchow commented
Yes, I made a change on my end earlier, and I saw that it updated the pull request.

2024-05-24 03:15 UTC, matiscke approved these changes
I reviewed all changes between `master` and [nwtuchow:HPIC_integration](https://github.com/nwtuchow/bioverse/tree/HPIC_integration) and all looks good to me. 

However, I don't have the bandwidth to actually test the new functionality right now - sorry. @kevinkhu were you able to run a quick test? Otherwise I can try next week.

I agree that there is little chance that merging this would break Bioverse. Still, before merging I think we should at a minimum:
- make a generator that includes the new HPIC function
- actually generate the planets
- see if the resulting Table object contains what is expected.

In any case, great work on this new addition to Bioverse!!

2024-05-24 03:15 UTC, matiscke commented on bioverse/Data/HPIC.txt
The catalog is ~< 2 MB, which is absolutely fine. No issue with size on disk.

2024-05-24 03:15 UTC, matiscke commented on bioverse/functions.py
This looks good and the new function has a descriptive docstring. Good stuff!

2024-06-07 00:39 UTC, matiscke commented
@nwtuchow Where would be a good place(s) in the [documentation](https://bioverse.readthedocs.io/en/latest/) to mention the possibility of planet generation with HPIC?

2024-06-10 17:25 UTC, nwtuchow commented
I think it might make sense to discuss it in the "Generating Planetary systems" section of the documentation. I think it would be also be helpful to describe the different options for the generator that are included with bioverse, such as the different functions for planet occurrence rates, generating host stars . The read_HPIC function could be described alongside the other functions

2025-09-09 22:08 UTC, closed without merging